[toolchain]
anchor_version = "0.28.0"
solana_version = "1.18.22"

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
psol = "2dJdyxoGmAoJLsZh7h8ma8xeyoaj7uiHFgrsgUAQMojv"
psol_token = "CgERkyXGARsLFqgBHyTk4Njyt7nyq9foJfmV7ptadYLy"

[programs.devnet]
psol = "2dJdyxoGmAoJLsZh7h8ma8xeyoaj7uiHFgrsgUAQMojv"
psol_token = "CgERkyXGARsLFqgBHyTk4Njyt7nyq9foJfmV7ptadYLy"

[programs.mainnet]
psol = "2dJdyxoGmAoJLsZh7h8ma8xeyoaj7uiHFgrsgUAQMojv"
psol_token = "CgERkyXGARsLFqgBHyTk4Njyt7nyq9foJfmV7ptadYLy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
